# Change these first
owner: wlky-0106 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nekoz Studio
    url: https://home.nekoz.top
  - name: Nekoz主页
    url: https://nekoz.top
  - name: Twikoo评论
    url: https://twikoo.nekoz.top/
  - name: Nekoz Studio Lark
    url: https://nekozstudio.larksuite.com/
  - name: 开源字体分享｜OFS
    url: https://learner.eu.org
  - name: Nekoz Upptime
    url: https://upptime.nekoz.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.nekoz.top
  # baseUrl: /your-repo-name
  logoUrl: https://nekoz.top/img/favico.png
  name: Nekoz Studio Upptime
  introTitle: "本页面是Nekoz Studio的系统监测页面"
  navbar:
    - title: Status
      href: /
    - title: 我的Blog
      href: https://Nekoz.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration'
i18n:
  activeIncidents: 活跃的事件
  allSystemsOperational: 所有系统都在运行
  incidentReport: "事件 #$NUMBER 报告 →"
  activeIncidentSummary: 在$DATE打开$POSTS
  incidentTitle: 事件 $NUMBER 详情
  incidentDetails: 事件 详情
  incidentFixed: 需要修复
  incidentOngoing: 正在进行中
  incidentOpenedAt: 打开于
  incidentClosedAt: 关闭于
  incidentViewOnGitHub: 在GitHub上查看和订阅
  incidentCommentSummary: $AUTHOR于$DATE发布
  incidentBack: ← 返回到所有事件
  pastIncidents: 过去的事故
  pastIncidentsResolved: 在$MINUTES时解决了$POSTS的问题
  liveStatus: 在线状态
  overallUptime: "总正常运行时间: $UPTIME"
  overallUptimeTitle: 总正常运行时间
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应时间
  sevelDayResponseTime: 7天平均响应时间
  responseTimeMs: 平均响应时间 (ms)
  up: 正常
  down: 停机
  degraded: 性能下降
  ms: ms
  loading: 加载中...
  navGitHub: GitHub
  footer: Copyright© 2021 - 2023 Nekoz Studio 
  rateLimitExceededTitle: 超出速率限制
  rateLimitExceededIntro: 你已经超过了一小时内可以完成的请求数量，所以你必须等待才能再次访问这个网站。另外，你可以添加一个GitHub个人访问令牌来继续使用这个网站。
  rateLimitExceededWhatDoesErrorMean: 这个错误是什么意思？
  rateLimitExceededErrorMeaning: 本网站使用GitHub API来访问有关我们网站状态的实时数据。默认情况下，GitHub允许每个IP地址每小时有60个请求，你已经消耗了这些请求。
  rateLimitExceededErrorHowCanFix: 我怎样才能修好它？
  rateLimitExceededErrorFix: 你可以再等一个小时，你的IP地址的限制将被恢复。另外，你可以添加你的GitHub个人访问令牌，这样你就可以获得每小时5000个额外的请求。
  rateLimitExceededGeneratePAT: 学习如何生成个人访问令牌
  rateLimitExceededHasSet: 你有一个个人访问令牌设置
  rateLimitExceededRemoveToken: 重制访问令牌
  rateLimitExceededGitHubPAT: GitHub的个人访问令牌
  rateLimitExceededCopyPastePAT: 复制并粘贴你的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 出现了一个错误
  errorIntro: 在试图获取最新的状态细节时发生了错误。
  errorText: 你可以过一会儿再试。
  errorHome: 进入主页
  pastScheduledMaintenance: 完成的定期维护
  scheduledMaintenance: 定期维护
  scheduledMaintenanceSummaryStarted: 从$DATE开始，持续时间为$DURATION分钟
  scheduledMaintenanceSummaryStarts: 从$DATE开始，持续时间为$DURATION分钟
  startedAt: 开始于
  startsAt: 开始于
  duration: 持续时间
  durationMin: $DURATION 分钟
  incidentCompleted: 已完成
  incidentScheduled: 预定
  duration24H: 24小时
  duration7D: 7天
  duration30D: 30天
  duration1Y: 1年
  durationAll: 全部

